= Notes for Accra Workshop, December 16-18, 2019

== Second Conference Call October 22, 2019

Present: Karen, Dave, Brinda, Scott, Hector, Willy, Moussa

Karen reviewed the documents sent last week. More detailed description of the workshop.

Moussa:

- NEPAD is OK with the proposed information to be presented, and the major divisions of the program.
- Case studies OK even if an application is not imminent. However, it will not be something that will be applied soon.
  Therefore, the details of the dossier is more important than the risk assessment aspect. He will discuss the program
  further with NEPAD. 
- Could we include something that deals with issues like the recent publication regarding Oxitec. This will make the
  workshop more useful to people in the short run. Also use this as an oppprtunity to improve their understanding of gene editing.

The underlying approach, consistent with Cartagena Protocol is that the process of risk assessment is the same as other
GMOs. There are specifics to gene drive that could be different, and those also should not be ignored.

Discussion:

Use the case studies as the driver for the workshop. Have the participants struggle with the document themselves and
identify where their knowledge gaps are. 

We will think about how we can incorporate this approach with the knowledge level of the participants in mind.  There
might not be people who are familiar enough  with dossiers without needing some guidance.

Will 2 days be enough? We will adjust the length of the workshop to fit our needs.

The workshop is highly technical.  People who will participate need to be picked carefully. Who will be the audience?
People who do the initial screening of applications? We should include the new Chairs of the Biosafety Committees
of Burkina Faso and Mali. Possible countries: Burkina Faso, Mali, Nigeria, Ghana.

Karen will make changes to the overview document.  Based on the revised overview, Moussa will discuss with NEPAD who the appropriate participants are. We will get an answer by Thursday.

What does NEPAD think of our proposed objectives and outcomes?

NEPAD has decided that Moussa will be the lead contact for the workshop.

== Third Conference Call

Discuss how we measure performance of learners and facilitators.
