= Conference call with NEPAD 2019-09-13

== Present: 

From NEPAD:  Hudu; Jeremy tried to join but was unsuccessful.
From FNIH:  Stephanie, Jeff S., Brinda, Dave, Renata

== Status of NEPAD proposal

Hudu:  NEPAD has received the request to submit their proposal.  The first submission should be ready by next week.

== Feedback on Maputo

None. Stephanie to discuss in separate call with Aggrey/Jeremy

== WAIVM

Unable to hold July and August meetings due to AUDA reorganization.

Next meeting will be 16-18 October in Accra for the 5 guidelines in advanced stages:

. IBC's
. Compliance monitoring
. Import and Export
. Testing gene drive arthropods (based on WHO guidance and Pathway document)
. Containment

A meeting to go over the ethics guidelines will be held 14-15 October, also in Accra.

Claudia Emerson and colleague will be at the ethics guidelines meeting. Participation by FNIH to be determined by Aggrey
and Jeremy.

== IBC's

Hudu:

Bobo--Three modules of training have been completed, 19-23 August, covering national laws and guidelines.  There will
be a meeting next week to decide on the next module of training (topic not mentioned).

Mali--approval for import given; eggs received.

== Additions by Brinda

A few details in addition to Hector’s notes:

16-18 Oct Accra meeting will be a subcommittee drawn from members of the WAIVM biosafety technical working group (TWG) and the steering committee. There will be a 3-4 week comment period for stakeholders to provide comments on the guidelines. NEPAD is expecting final approval by the Steering committee sometime in November of 2019.

 

The Ethics TWG will meet to work on the ethics guidelines which are not as advanced as the other 5 guidelines due to the TWG requesting the initial draft be redone.

 

On the IBCs my notes are a bit different from Hector’s. I heard Hudu say that the Burkina Faso ANB has 3 training modules which need to be provided/completed by IRSS before the final administrative establishment of the IBC is possible. So far 2 of these 3 modules have been delivered during the 19-23 Aug training. There is a meeting scheduled for next week to decide on dates for the 3rd module to be provided. Additionally we were told that IRSS is now a center of excellence funded by the World Bank.

 

 

Thanks

Brinda
