= Face to Face Meeting with NEPAD 2019-12-09
:sectnums:

Place: FNIH Offices, Rockville, MD +
Time: 1:00 - 5:00 PM +
Present: Aggrey Ambali, Hudu Mogtari, Jeremy Ouedraogo, Brinda Dass, David O'Brochta, Hector Quemada, Karen Tountas, Mike Santos, Stephanie James, Susan Weiner

== News from FNIH and AUDA-NEPAD 

=== FNIH 
Grant has been approved.

Mike Santos introduced as new member of the team.

=== NEPAD
Since August, institutional reorganization, from NEPAD to AUDA.
Five directorates.
Headquarters will remain in South Africa.
Legal status change: AUDA can engage in its own agreements (?).

The grant has been submitted for comment to BMGF

=== FNIH Activities in 2019
Reviewed technical workshops held.
Genome editing is a key component of AUDA's 2020 plan, so Dave's workshop on gene editing could be helpful to their plan.

Discussion on release strategy--UCI direct release of gene drive vs. Target Malaria staged approach.

=== NEPAD 2019
Activities focused on WAIVM regional platform.

==== WAIVM
West Africa was the pilot region; will scale up to the continent.

Steering committee inaugurated the Technical Working Groups.
Consisted of agencies from biosafety, health, environment.
Biosafety focal points also attended the meeting.

Dedicated session for IVM Health Regulators.
To discover their expectations for gene drive regulation.
To "demistify" gene drive

Draft zero IVM guidelines reviewed by select four before going to Technical Working Groups.

Reviewed first set of guidelines by TWGs in June in Dakar.
There were five guidelines.
All 15 member states attended.

Reviewed the Ethics guidelines prepared by Ethics TWG in November.

All 5 guidelines reviewed in November.

Validation of the guidelines right after.
[Validation seems to have entailed checking whether the guidelines were consistent with national regulations.]

Will disseminate the guidelines for external comments (15 December 2019 - 15 January 2020).

==== Individual country updates
Burkina Faso: Lesson learned--make sure all agencies are involved.
The new head of the ANB has good relationship with Jeremy.
He is positive on emerging technologies.

Mali: Need to get the biosafety focal point well trained; AUDA will focus on it.
Need to establish an IBC and a national authority.
Plan to conduct study tours to Burkina.

Developers on the ground need to avoid misunderstandings. NEPAD has put in place mechanisms for how Target Malaria interacts with the government.
Communication with government needs to improve.

==== WAHO
Linda Omosefe has been put in place in WAHO.

==== Uganda
Sunday Akile is keeping track of events there.
Yona Baguma is working on how the restrictive provisions of the draft law might be deal with.

==== Regulatory Workshops
Presented on results and lessons learned from 2019 workshop.

The Minister of Rwanda had to deliver biosafety policy and regulation by the end of the year, so NEPAD had to focus on that.
That's the reason why they couldn't focus on the Accra workshop

== AUDA plan for 2020
Consolidate progress in West Africa.
Scale up to continental level 
COP/MOP

=== Enhance understanding and greater awareness on genetically based vector control and its application for human health
Geared to key leaders.
==== sensitization workshop and annual updates
==== regional and international site visits and trial progress updates.

=== Facilitate social acceptance (advocacy)
==== Facilitated dialogues, convenings, partnerships and communication to enhance acceptance
==== Support the work of the AU High Level Panel and the development of a communications strategy on gene drive.

=== Enhance capacity of African regulators (health, environment, biosafety)
Fill the gaps that they feel they need more help on.
Capacity strengthening of regulators, including

==== gap assessments
==== curricula development, based on the guidelines that have been developed.
==== country specific and regional training sessions
* testing GM mosquitoes
* IBCs
* compliance monitoring and inspection
* containment facilities
* bioethics and public engagement

=== Operationalize regional and continental regulatory platforms for IVM

=== Establish a continental advisory panel

=== Enhance international engagements for African regulators
==== negotiation training ahead of key meetings
==== preparation sessions
==== support for representatives to go to COP/MOP 

=== Conclusion on workshops for 2020
It looks like there will probably be fewer workshops like the ones we have envisioned, but those that will be done will come out of the engagements that AUDA will do.
There is agreement that we will do the Accra workshop.
Now that we have developed the content, the question going forward will be when we will be available to use it.
They shared their workplan so that we will be able to better determine where we can contribute, and where our consultative workshops will be useful.
They would also like to have us participate in the Technical Working Group.

