=  Notes for Online Forum
:sectnums:

== From Dave O'Brochta

=== The first sentence of the Executive Summary.  “Gene drive allow for a trait to be distributed across generations deviating from the laws of Mendelian inheritance”.

First, there are no ‘laws’ in biology.  Certainly, not in the sense of physical laws.

But given that the “Mendel’s laws” meme exists – gene drive and selfish genetic elements do not break them.  “Law” of segregation?  Not broken.  “Law” of independent assortment.  Not broken by homing drives, underdominance, and most meiotic drives (there are selfish genetic elements that do operate by manipulating ‘assortment’ – but no engineered drives.  There are some selfish genetic elements that avoid ending up in polar bodies during oocyte development).

So – no ‘laws’ are broken.  Why is this important?  Because it plays into the ‘un/naturalness’ argument and the first sentence basically says that gene drives are ‘unnatural’.

== Second sentence of Executive Summary.  “…increase in frequency independent of external selection pressure”.

This is inaccurate.  The extent to which a selfish genetic element increases in frequency will absolutely be a function of its fitness effects.  To indicate that fitness effects are irrelevant is to misunderstand the genetics but more importantly it furthers the ‘un/naturalness’ argument.

Again, the author is saying the gene drives are doing things that are ‘unnatural’

